=== kdrakon/axmlt-Implementation/Experimentation/XML Schema for Axmlt/axmlt_policybase.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema elementFormDefault="qualified"
	targetNamespace="scm.uws.edu.au"
	xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns:axmlt="scm.uws.edu.au">

	<xs:element name="policybase">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="rule" minOccurs="0"
					maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="head-statement"
								minOccurs="1" maxOccurs="1" type="axmlt:statement-types">
							</xs:element>
							<xs:element name="body-statement"
								type="axmlt:statement-types" maxOccurs="unbounded"
								minOccurs="0">
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="statement-types">
		<xs:choice>
			<xs:element name="relationship-statement"
				type="axmlt:relationship-atom" maxOccurs="1" minOccurs="1">
			</xs:element>
			<xs:element name="grant-statement" type="axmlt:grant-atom"
				maxOccurs="1" minOccurs="1">
			</xs:element>
			<xs:element name="role-statement" type="axmlt:role-atom"
				maxOccurs="1" minOccurs="1">
			</xs:element>
		</xs:choice>
		<xs:attribute name="withAbsence" type="xs:boolean" use="optional" default="0"></xs:attribute>
	</xs:complexType>

	<xs:complexType name="relationship-atom">
		<xs:choice>
			<xs:element name="below" type="axmlt:relationship-tuple" maxOccurs="1" minOccurs="1"></xs:element>
			<xs:element name="separate" type="axmlt:relationship-tuple" maxOccurs="1" minOccurs="1"></xs:element>
			<xs:element name="during" type="axmlt:relationship-tuple" maxOccurs="1" minOccurs="1"></xs:element>
			<xs:element name="starts" type="axmlt:relationship-tuple" maxOccurs="1" minOccurs="1"></xs:element>
			<xs:element name="finishes" type="axmlt:relationship-tuple" maxOccurs="1" minOccurs="1"></xs:element>
			<xs:element name="before" type="axmlt:relationship-tuple" maxOccurs="1" minOccurs="1"></xs:element>
			<xs:element name="overlap" type="axmlt:relationship-tuple" maxOccurs="1" minOccurs="1"></xs:element>
			<xs:element name="meets" type="axmlt:relationship-tuple" maxOccurs="1" minOccurs="1"></xs:element>
			<xs:element name="equal" type="axmlt:relationship-tuple" maxOccurs="1" minOccurs="1"></xs:element>
		</xs:choice>
	</xs:complexType>

	<xs:complexType name="relationship-tuple">
		<xs:sequence>
			<xs:element name="value1" type="xs:string" maxOccurs="1"
				minOccurs="1">
			</xs:element>
			<xs:element name="value2" type="xs:string" maxOccurs="1"
				minOccurs="1">
			</xs:element>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="grant-atom">
		<xs:sequence>

			<xs:element name="role-name" type="xs:string" maxOccurs="1" minOccurs="1"></xs:element>
			<xs:element name="subject" type="xs:string" maxOccurs="1" minOccurs="1"></xs:element>
			<xs:element name="temporal-interval" type="xs:string" maxOccurs="1" minOccurs="1"></xs:element>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="role-atom">
		<xs:sequence>
			<xs:element name="role-name" type="xs:string" maxOccurs="1" minOccurs="1"></xs:element>
			<xs:element name="sign" type="xs:string" maxOccurs="1" minOccurs="1"></xs:element>

			<xs:element name="xpath-statement" type="axmlt:xpath-atom" maxOccurs="1" minOccurs="1"></xs:element>
			<xs:element name="privilege" type="xs:string" maxOccurs="1" minOccurs="1"></xs:element>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="xpath-atom">
		<xs:sequence>
			<xs:element name="document-name" type="xs:string"
				maxOccurs="1" minOccurs="1">
			</xs:element>
			<xs:element name="xpath-expression" type="xs:string" maxOccurs="1" minOccurs="1"></xs:element>
		</xs:sequence>
	</xs:complexType>

</xs:schema>

=== kdrakon/axmlt-Implementation/Experimentation/XML Schema for Axmlt/sample_pb.xml
<?xml version="1.0" encoding="UTF-8"?>
<axmlt:policybase xmlns:axmlt="scm.uws.edu.au" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="scm.uws.edu.au axmlt_policybase.xsd ">
  <axmlt:rule>
    <axmlt:head-statement>
      <axmlt:relationship-statement>
        <axmlt:below>
          <axmlt:value1>axmlt:value1</axmlt:value1>
          <axmlt:value2>axmlt:value2</axmlt:value2>
        </axmlt:below>
      </axmlt:relationship-statement>
    </axmlt:head-statement>
    <axmlt:body-statement>
      <axmlt:relationship-statement>
        <axmlt:below>
          <axmlt:value1>axmlt:value1</axmlt:value1>
          <axmlt:value2>axmlt:value2</axmlt:value2>
        </axmlt:below>
      </axmlt:relationship-statement>
    </axmlt:body-statement>
  </axmlt:rule>
    <axmlt:rule>
    <axmlt:head-statement>
      <axmlt:relationship-statement>
        <axmlt:below>
          <axmlt:value1>axmlt:value1</axmlt:value1>
          <axmlt:value2>axmlt:value2</axmlt:value2>
        </axmlt:below>
      </axmlt:relationship-statement>
    </axmlt:head-statement>
    <axmlt:body-statement>
      <axmlt:relationship-statement>
        <axmlt:below>
          <axmlt:value1>axmlt:value1</axmlt:value1>
          <axmlt:value2>axmlt:value2</axmlt:value2>
        </axmlt:below>
      </axmlt:relationship-statement>
    </axmlt:body-statement>
    <axmlt:body-statement>
      <axmlt:relationship-statement>
        <axmlt:below>
          <axmlt:value1>axmlt:value1</axmlt:value1>
          <axmlt:value2>axmlt:value2</axmlt:value2>
        </axmlt:below>
      </axmlt:relationship-statement>
    </axmlt:body-statement>    
  </axmlt:rule>
</axmlt:policybase>

=== kdrakon/axmlt-Implementation/Public/pb.xml
<?xml version="1.0" ?><axmlt:policybase xmlns:axmlt="scm.uws.edu.au" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="scm.uws.edu.au axmlt_policybase.xsd ">
  
    
      
  
            
<axmlt:rule><axmlt:head-statement><axmlt:role-statement><axmlt:role-name>volunteer</axmlt:role-name><axmlt:sign>pp</axmlt:sign><axmlt:xpath-statement><axmlt:document-name>nutrition</axmlt:document-name><axmlt:xpath-expression>//carb</axmlt:xpath-expression></axmlt:xpath-statement><axmlt:privilege>read</axmlt:privilege></axmlt:role-statement></axmlt:head-statement></axmlt:rule><axmlt:rule><axmlt:head-statement><axmlt:role-statement><axmlt:role-name>employee</axmlt:role-name><axmlt:sign>pp</axmlt:sign><axmlt:xpath-statement><axmlt:document-name>nutrition</axmlt:document-name><axmlt:xpath-expression>/</axmlt:xpath-expression></axmlt:xpath-statement><axmlt:privilege>read</axmlt:privilege></axmlt:role-statement></axmlt:head-statement></axmlt:rule><axmlt:rule><axmlt:head-statement><axmlt:relationship-statement><axmlt:below><axmlt:value1>nutritionist</axmlt:value1><axmlt:value2>employee</axmlt:value2></axmlt:below></axmlt:relationship-statement></axmlt:head-statement></axmlt:rule><axmlt:rule><axmlt:head-statement><axmlt:role-statement><axmlt:role-name>nutritionist</axmlt:role-name><axmlt:sign>pp</axmlt:sign><axmlt:xpath-statement><axmlt:document-name>nutrition</axmlt:document-name><axmlt:xpath-expression>/</axmlt:xpath-expression></axmlt:xpath-statement><axmlt:privilege>write</axmlt:privilege></axmlt:role-statement></axmlt:head-statement></axmlt:rule><axmlt:rule><axmlt:head-statement><axmlt:role-statement><axmlt:role-name>volunteer</axmlt:role-name><axmlt:sign>pp</axmlt:sign><axmlt:xpath-statement><axmlt:document-name>nutrition</axmlt:document-name><axmlt:xpath-expression>//calories[@fat='100']</axmlt:xpath-expression></axmlt:xpath-statement><axmlt:privilege>read</axmlt:privilege></axmlt:role-statement></axmlt:head-statement></axmlt:rule><axmlt:rule><axmlt:head-statement><axmlt:relationship-statement><axmlt:separate><axmlt:value1>nutritionist</axmlt:value1><axmlt:value2>employee</axmlt:value2></axmlt:separate></axmlt:relationship-statement></axmlt:head-statement></axmlt:rule><axmlt:rule><axmlt:head-statement><axmlt:grant-statement><axmlt:role-name>nutritionist</axmlt:role-name><axmlt:subject>sean</axmlt:subject><axmlt:temporal-interval>monday</axmlt:temporal-interval></axmlt:grant-statement></axmlt:head-statement></axmlt:rule><axmlt:rule><axmlt:head-statement><axmlt:grant-statement><axmlt:role-name>doctor</axmlt:role-name><axmlt:subject>pat</axmlt:subject><axmlt:temporal-interval>wednesday</axmlt:temporal-interval></axmlt:grant-statement></axmlt:head-statement></axmlt:rule><axmlt:rule><axmlt:head-statement><axmlt:role-statement><axmlt:role-name>doctor</axmlt:role-name><axmlt:sign>pp</axmlt:sign><axmlt:xpath-statement><axmlt:document-name>nutrition</axmlt:document-name><axmlt:xpath-expression>/dailyvalues</axmlt:xpath-expression></axmlt:xpath-statement><axmlt:privilege>write</axmlt:privilege></axmlt:role-statement></axmlt:head-statement></axmlt:rule><axmlt:rule><axmlt:head-statement><axmlt:role-statement><axmlt:role-name>nutritionist</axmlt:role-name><axmlt:sign>mm</axmlt:sign><axmlt:xpath-statement><axmlt:document-name>nutrition</axmlt:document-name><axmlt:xpath-expression>/dailyvalues</axmlt:xpath-expression></axmlt:xpath-statement><axmlt:privilege>write</axmlt:privilege></axmlt:role-statement></axmlt:head-statement></axmlt:rule><axmlt:rule><axmlt:head-statement><axmlt:grant-statement><axmlt:role-name>nutritionist</axmlt:role-name><axmlt:subject>pat</axmlt:subject><axmlt:temporal-interval>wednesday</axmlt:temporal-interval></axmlt:grant-statement></axmlt:head-statement></axmlt:rule><axmlt:rule><axmlt:head-statement><axmlt:relationship-statement><axmlt:before><axmlt:value1>monday</axmlt:value1><axmlt:value2>tuesday</axmlt:value2></axmlt:before></axmlt:relationship-statement></axmlt:head-statement></axmlt:rule><axmlt:rule><axmlt:head-statement><axmlt:relationship-statement><axmlt:before><axmlt:value1>tuesday</axmlt:value1><axmlt:value2>wednesday</axmlt:value2></axmlt:before></axmlt:relationship-statement></axmlt:head-statement></axmlt:rule><axmlt:rule><axmlt:head-statement><axmlt:grant-statement><axmlt:role-name>volunteer</axmlt:role-name><axmlt:subject>joel</axmlt:subject><axmlt:temporal-interval>tuesday</axmlt:temporal-interval></axmlt:grant-statement></axmlt:head-statement></axmlt:rule><axmlt:rule><axmlt:head-statement><axmlt:grant-statement><axmlt:role-name>doctor</axmlt:role-name><axmlt:subject>joel</axmlt:subject><axmlt:temporal-interval>friday</axmlt:temporal-interval></axmlt:grant-statement></axmlt:head-statement></axmlt:rule><axmlt:rule><axmlt:head-statement><axmlt:relationship-statement><axmlt:during><axmlt:value1>teatime</axmlt:value1><axmlt:value2>morning</axmlt:value2></axmlt:during></axmlt:relationship-statement></axmlt:head-statement></axmlt:rule></axmlt:policybase>

=== kdrakon/axmlt-Implementation/Public/newRule.xml
<?xml version="1.0"?>
<axmlt:policybase xmlns:axmlt="scm.uws.edu.au" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="scm.uws.edu.au axmlt_policybase.xsd"><axmlt:rule><axmlt:head-statement><axmlt:grant-statement><axmlt:role-name>X</axmlt:role-name><axmlt:subject>Y</axmlt:subject><axmlt:temporal-interval>Z</axmlt:temporal-interval></axmlt:grant-statement></axmlt:head-statement><axmlt:body-statement><axmlt:relationship-statement><axmlt:below><axmlt:value1>X</axmlt:value1><axmlt:value2>A</axmlt:value2></axmlt:below></axmlt:relationship-statement></axmlt:body-statement><axmlt:body-statement><axmlt:relationship-statement><axmlt:during><axmlt:value1>Z</axmlt:value1><axmlt:value2>tuesday</axmlt:value2></axmlt:during></axmlt:relationship-statement></axmlt:body-statement></axmlt:rule></axmlt:policybase>
